### ISSUE TITLE
Application-specific functions and E2E

### ISSUE THREAD

**Issue by ekr** [IRTF-HRPC/draft-guidelines#1]
S 4.1.

>    Question(s): Does your protocol add application-specific functions to
   intermediary nodes?  Could this functionality be added to end nodes
   instead of intermediary nodes?
...

>    Explanation: The end-to-end principle [Saltzer] holds that certain
   functions can and should be performed at ‘ends’ of the network.
   [RFC1958] states “that in very general terms, the community believes
   that the goal is connectivity […] and the intelligence is end to end
   rather than hidden in the network.” Generally speaking, it is easier
   to attain reliability of data transmissions with computation at
   endpoints rather than at intermediary nodes.

I think this really oversimplifies the application of the end-to-end argument in this setting. While I think the e2e argument is generally sound for simple systems, ISTM that the experience with designing large scale protocols is actually that having a lot of the computation in intermediate nodes makes reliability much easier, for a number of reasons, including:

- It's robust to the endpoints not being connected at the same time
- It can help compensate for endpoint failures (e.g., devices being lost
- It helps deal with network filtering scenarios.

For content distribution applications, it actually scales better to network topologies (e.g., P2P versus CDNs). 

These are just some of the reasons why so many applications--even those which provide features like end-to-end encryption--tend to be somewhat centralized at the transport layer.

I also think this question "Could this functionality be added to end nodes instead of intermediary nodes?" is not really that helpful. This seems like kind of an unhelpful framing, because there are of course designs which *can* have functionality at the end nodes but it doesn't work well in terms of factors like those above. My main point here is that in practice, e2e is one factor among many in design, and I don't think this really comes across

**Comment by gurshabad** [comment]
Thanks, ekr. First, we agree that the e2ee principle is a sound principle for protocol design. I also agree that there are other considerations/principles at play (for the reasons you have outlined, even though I am personally against the network filtering consideration). 

Will it be reasonable to add something along these lines as another question: "If you are adding functions to intermediary nodes, are you documenting the reasons for doing so?"

**Comment by ekr** [comment]
> Thanks, ekr. First, we agree that the e2ee principle is a sound principle for protocol design. 

You will note that I said "for simple systems". I think the available evidence does not support the claim that it is a sound principle for complex systems.


> I also agree that there are other considerations/principles at play (for the reasons you have outlined, even though I am personally against the network filtering consideration).

I don't understand what it means to be "against" these considerations. It's a simple fact that it's not possible to design P2P systems that work through NATs and firewalls 100% of the time without having some kind of relay server (e.g., TURN). So you can either have such a server or you can have pairs of clients not able to talk to each other. 


> Will it be reasonable to add something along these lines as another question: "If you are adding functions to intermediary nodes, are you documenting the reasons for doing so?"

No, I don't think so. The problem here is that the gist of this sxn is that E2E is the default and that you need to justify any deviation from that, but that's contrary to most of the design of Internet services, which tend towards client/server architectures and often to centrality. So I think this whole section comes off as out of touch.

**Comment by nllz** [comment]
As far as I understand, the IETF position is that the end-to-end principle is a core architectural principle, and every protocol design should take it into account. See RFC3724.

If you think this is not the IETF position, or you think protocol design should NOT take the E2E principle into account at all, that discussion may belong in other lists such as arch-discuss, etc.

**Comment by ekr** [comment]
> As far as I understand, the IETF position is that the end-to-end principle is a core architectural principle, and every
> protocol design should take it into account. See RFC3724.

RFC 3724 is an IAB document and may or may not reflect IETF consensus,
so isn't dispositive in this case.


> If you think this is not the IETF position, or you think protocol design should NOT take the E2E principle into account at all, that discussion may belong in other lists such as arch-discuss, etc.

That is not my position. Rather, my position is that a very large fraction
of IETF protocols use client/server architectures and that it is not the
position of the IETF that every time one designs such a system there
ought to be an extensive inquiry into whether a server was really
needed in each part of the system where it is used.

**Comment by nllz** [comment]
No one asked for an extensive inquiry. And if this really is standing practice, it should not be hard to explain this design choice, right?

**Comment by ekr** [comment]
I don't think that we should be asking protocol designers to justify standard design practices. This just seems like makework.

**Comment by nllz** [comment]
I think this example exactly shows that what is a 'standard design practice' can wildly change over the years. I don't think for an organizations of standards developers it should be hard to document why they do what they do.

**Comment by ekr** [comment]
The question is not whether it's hard to document any individual design choice but rather the administrative burden of being asked to do so in every case is reasonable.

To take a different example, the standard IETF practice is to use "network" (big-endian) byte order, even though this is actually not that convenient for many processors, and I know a number of designers who would prefer little-endian. I think there are good reasons for using big-endian, but I don't think it would be reasonable to ask designers to include a section in each protocol explaining their endianness choice.

**Comment by nllz** [comment]
Luckily the guidelines are not asking to explain in each protocol their endianness choice, let alone mandate.

If a developer feels strongly about this, and thinks it is very relevant adding something like the following should not be an 'administrative burden', right?

"In this protocol, the network byte order is defined to always be big-endian, which may differ from the host byte order on a particular machine. Using network byte ordering for data exchanged between hosts allows hosts using different architectures to exchange address information without confusion because of byte ordering, while using little-endian could actually be beneficial in case X, Y, and Z. However, because the consensus in the network is big-endian, we are following this practice."

**Comment by ekr** [comment]
My point here is that asking people to justify such a common pattern as client/server is makework in the same way as aking them to justify endianness choices is. And yes, having to add the kind of boilerplate you suggest for endianness would be administrative burden. About the only exception I can think of is a protocol which started little-endian and was then switched, like QUIC.

**Comment by nllz** [comment]
I think while there is quite a bit of discussion on centralization - it might be very useful to discuss client/server vs end-to-end. But we can also agree to disagree here, especially since we came to the conclusion this is not a technical misrepresentation of any kind.

**Comment by ekr** [comment]
I don't know if it's a "misrepresentation" but I think it's wrong, for the reasons indicated in my initial comment.

**Comment by nllz** [comment]
You think it is wrong because it  creates, what you call, 'an administrative burden', right? Or is there something you think is technically wrong?

**Comment by ekr** [comment]
No. I think it's wrong in that it implies that the default/best way to design systems is with the intelligence in the endpoints and that client/server architectures are somehow an exception that needs justification. While there are indeed many settings in which this is a good idea, it is not reflective of much standard IETF engineering practice.

**Comment by nllz** [comment]
I am sorry but the text does not say that. And again, am more than happy to review text suggestions. That probably helps us ahead more than debating what is or what is not implied.

**Comment by ekr** [comment]
My suggestion would be to strike the entire section.

**Comment by nllz** [comment]
If your argument for deleting an entire section is that you think the text implies something that it does not literally say, and you don't want to suggest other text, it will be hard to come to agreement here.

**Comment by ekr** [comment]
My argument is contained in the comment that created the issue. Everything
else is us just debating.

**Comment by nllz** [comment]
Your argument departs from an assumption that is simply not supported by the text in the draft that is there. So I am very sorry, but if you don't want to work on a joint solution there is very little I can do.

**Comment by nllz** [comment]
Would it help if we put in some text on how different designs might be apt for different circumstances and that this is why documenting the choice is beneficial? Or a reference to RFC3724 ?

**Comment by ekr** [comment]
Not really, no. My basic objection here is that this text overgeneralizes the experience from data transmission, where I agree that E2E designs are good (though often with a lot more in-network assistance than is acknowledged), to overall systems designs, which are in many cases client/server. Specifically, the text asks you answer this question:

> Question(s): Does your protocol add application-specific functions to
intermediary nodes? Could this functionality be added to end nodes
instead of intermediary nodes?

and then provides an explanation based on Saltzer's classic E2E paper, which is really about a more limited domain.

Upon reflection, perhaps we are just talking past each other. I see that draft-thomson-tmi draws the distinction between "intermediaries" and "services" (https://datatracker.ietf.org/doc/html/draft-thomson-tmi-04#section-9.1). In this discussion, i have been primarily talking about client/server architectures, which I think are necessary in many cases. However, if we agreed that this text applied only to intermediaries in the sense that draft uses them, then i think I would agree with the sentiment, and I'd be happy to provide a PR making that clear.

**Comment by nllz** [comment]
Yes! We can agree on that!

**Comment by ekr** [comment]
Great. I don't have permissions for this repo, but perhaps you could tag this issue as PR-needed or something?
