### ISSUE TITLE
Permissionless innovation/adaptability scope

### ISSUE THREAD

**Issue by ekr** [IRTF-HRPC/draft-guidelines#4]
Section 4.8 says:

>   Question(s): Is your protocol written in such a way that it would be
   easy for other protocols to be developed on top of it, or to interact
   with it?  Does your protocol impact permissionless innovation?  (See
   Open Standards)

This seems like it applies to a fairly narrow set of protocols
(e.g., transport protocols). For instance, what does it mean for
a new protocol to be "developed on top" of Certificate Transparency
or PKIX?

**Comment by gurshabad** [comment]
I think it's okay if it applies to a narrow set of protocols. The question does say "protocol" and not "standard", but please feel free to suggest text if you think it makes the principle's application clearer.

**Comment by ekr** [comment]
Well CT and PKIX are certainly protocols.

More generally, I don't really understand what it is that this section is trying to say. Can you give an example of a protocol that wasn't designed to allow permissionless innovation?

**Comment by nllz** [comment]
The IETF respects this principle (see: https://www.ietf.org/blog/permissionless-innovation/). And that's a good thing. No harm in repeating good ideas.

This document aims to inform protocol designers and standards everywhere, not just at the IETF.

**Comment by ekr** [comment]
@gurshabad @nllz I don't think either of your comments is really responsive to my points.

To repeat them:
1. Many protocols are not suitable for having other protocols built on them, not because of the design of the protocol but due to the position they occupy in the protocol stack.
2. What is the actual force of this text? What would it mean for a protocol to *not* enable permissionless innovation?

**Comment by nllz** [comment]
Maybe 'on top' is not the best metaphor, but neither is 'alongside'. In conjunction perhaps? It would be great if you could help suggest text that works for you.

For a protocol to disable permissionless innovation it would mean that is would disallow the deployment of alternative technologies of implementations.

**Comment by csperkins** [comment]
I wonder if this might be better phrased in terms of (i) the range of use cases that a protocol supports, and whether it's tightly focussed on solving one specific problem or is structured in a way that supports a broader range of related uses; and (ii) the extent to which a protocol has built-in extension points to allow it to be adapted to new uses over time.

The focus on layering seems to reflect a very narrow view of the protocol stack. 

"Does your protocol impact permissionless innovation?" – I'm not sure I understand the question. Every protocol is either a new innovation in itself, or it opens up new extension points or enables new uses for the network, or it closes-off some particular direction to future innovation. All of these impact permissionless innovation in *some* way. A more interesting question is what impact does it have on future uses of the network.

**Comment by nllz** [comment]
While every protocol may be an innovation, that doesn't mean that it enables for future innovation. Therefore, the question: does it enable permissionless innovation, or does it hamper it. I agree the stack implication 'on top of' might not be helpful. If you both agree I will suggest new text along these lines.

**Comment by ekr** [comment]
I don't think it's just about "on top of".

My sense is that this text and the idea that the IETF is interested in permissionless innovation sort of mashes up a number of concepts:

1. IETF protocols are designed in the open and then free to use and modify (and also try to avoid patents) so whatever their technical content, they allow for permissionless innovation in a way that other protocols might not.
2. IETF protocols are often designed in a modular and extensible fashion so that it is possible to take a protocol and repurpose it (what Colin says above).
3. IETF protocols are sometimes designed in a way that favors architectures that themselves allow for permissionless innovation.

FWIW, I think that "sometimes" is doing a lot of work in (3). While there certainly aspects in which our protocols do favor such architectures, I think it's also clear that in many cases our protocols have favored forms of centralization that allowed permissionless innovation for some but not others. To take a good example, the architecture of the Web has made it so that a few entities (especially Google, but also other players) are able to innovate on the core protocols (e.g., QUIC) but that if you're not one of those players, innovation is much more difficult. One might imagine that some kind of decentralized system would do better (though maybe not, as innovation in Blockchain systems seems to be quite challenging).  

My sense is that it's actually fairly hard to reason a priori about which designs will do well in this regard. After all, the Web and other protocols such as SMTP are nominally federated, but in practice have become quite centralized with this result of concentrating innovation. Could we have anticipated this in advance? Not sure!

My put would be to lean into the sense that Colin indicates in his comments, namely are the protocols modular and extensible.  Those are the properties that allow the protocols to be used for innovation, even if the systems that are built with them are not.

**Comment by nllz** [comment]
Excellent - so may I proposed the following:

Question: Is your protocol written in a modular fashion and does it facilitate or hamper extensibility? In this sense, does your protocol impact permissionless innovation? (See Open Standards)

**Comment by ekr** [comment]
I can live with this.

**Comment by nllz** [comment]
Perfect - done! https://github.com/IRTF-HRPC/draft-guidelines/commit/12b572185472f4a8954e3e82f8b2d09a50531c64
