### ISSUE TITLE
Remedy

### ISSUE THREAD

**Issue by ekr** [IRTF-HRPC/draft-guidelines#6]
>   Question(s): Can your protocol facilitate a negatively impacted
>   party’s right to remedy without disproportionately impacting other
>   parties’ human rights, especially their right to privacy?
>
>   Explanation: Providing access to remedy by states and corporations is
>   a part of the UN Guiding Principles on Business and Human Rights
>   [UNGP].  Access to remedy may help victims of human rights violations
>   in seeking justice, or allow law enforcement agencies to identify a
>   possible violator.  However, mechanisms in protocols that try to
>   enable ‘attribution’ to individuals will impede the exercise of the
>   right to privacy.  The former UN Special Rapporteur for Freedom of
>   Expression has also argued that anonymity is an inherent part of
>   freedom of expression [Kaye].  Considering the potential adverse
>   impact of attribution on the right to privacy and freedom of
>   expression, enabling attribution on an individual level is most
>   likely not consistent with human rights.
>
>   Example: Adding personally identifiable information to data streams
>   might help in identifying a violator of human rights and provide
>   access to remedy, but this would disproportionally affect all users
>   right to privacy, anonymous expression, and association.
>
>   Example: There are some recent advances in enabling abuse detection
>   in end-to-end encrypted messaging systems, which also carry some risk
>   to users’ privacy. [messenger-franking][hecate]

This seems to sort of jumble up a bunch of different concepts.

# Identifying information versus proof

It's very common for systems to have identifying information in them
but for that information to not be third-party verifiable
("nonrepudiable"). This is often the case when messages are not
signed, as, for instance, in Signal. In these systems, it can be
difficult to prove that a given message came from someone else.
Franking is an example of a technology that tries to allow this.  In
MLS, however, messages are just signed because the WG took the
position that real deniability was out of scope.  I don't think this
document should take a position on this debate.

# The right to privacy versus attribution

There are also situations in which there is no identifying information
and people are talking about adding some for attribution (the persistent
calls for "Internet drivers licenses", for instance). I generally
feel like this is unworkable for a bunch of operational reasons and
am not a fan of the privacy implications eitehr, but I also think
this document should take a position on this, as it seems like there
might be situations where the right to anonymity is outweighed by
other values (e.g., abuse prevention.

Is it really the position of the RG that there are no situations in
which people should be required to identify (even pseudonymously) to
engage in a conversation? That seems like a fairly extreme position,
and really runs counter to a lot of the IETF's anti-abuse activity.
I do think we should try to avoid designing protocols which require
unnecessary attribution, but like I said, I don't think it's the only
value.

**Comment by ekr** [comment]
Following up a bit: given that I think that this current phrasing is
too absolute, in order to be useful it would be better if it provided
some discussion of tradeoffs and some examples of where the
RG thinks they were good and bad.

**Comment by mallory** [comment]
For context as doc shepherd, this text was negotiated extensively on the list in 2021.

In my view, the text does not benefit from adding the first section of text on proof because it does not curretly read as within scope.

The latter text gets to the heart of the intention of the text. And here I would remind everyone that this is about tradeoffs. This is exactly the careful result of the extensive list activity. I don't think that we can change it now.

Appreciate the support for why this text is important, ekr, but unless the authors see a way to soften the position without totally re-hashing a RG-wide consensus discussion about it, I think this issue is a wont-fix.

**Comment by csperkins** [comment]
If I'm reading EKR's comment correctly, he's saying that (1) there is an important technical point that has been missed in the discussion; and (2) that the draft is proposing a position that's counter to the IETF consensus on how to address the issue.

For the first point, given the example ("Adding personally identifiable information to data streams might help in identifying a violator of human rights and provide access to remedy") I'd argue that new information about technical constraints on the ability to verify such personally identifiable information is in scope. It may, or may not, lead to changes in the draft when discussed, but the new information should be considered.

On the second point, the RG is free to come to a consensus that's counter to the way IETF does things. It's a research group, and *of course* sometimes the outcome of research is to say that current practise is inappropriate. But, if the group comes to such a consensus, I'd argue that it's important that it clearly explain and justify the difference in view.

**Comment by ekr** [comment]
I think this is a fair characterization, yes.

On point (1) In my experience it's very rare to have communication systems which truly have no identifying information at all, even at the layer available to users (it's of course essentially unknown to have no identifiers at all because the network uses them for routing). For instance, e-mail systems have addresses, most messaging systems have handles or phone numbers, etc.

Rather, the cut point is between:

(1) Systems which allow the recipient to prove what was sent rather than just assert it.
(2) Systems where the identifying information that is provided is tied to real world identities more than is necessary to facilitate continuity of communication (e.g., Real Names policies, etc.)

I don't think my comment above does that great a job of pulling out this second. Sorry about that.

I *do* think that there are situations where people have proposed (2) that would be harmful to privacy, for instance "Internet Driver's Licenses", etc., but I think the abstraction level of this text makes it very hard to see that. What I think would be helpful in this discussion here would be if the authors were to provide a few examples of situations where systems have been proposed or do what they are objecting to "Adding personally identifiable...." and then we can try to craft some text that captures those notions. Those examples may or may not end up in the text but they would help us frame the issue in this discussion.


Taking a step back, this document is intended to provide guidance, at least at the level of the RG's opinion, and I'm having trouble understanding what that guidance is. Suppose that I were designing a new instant messaging system inside the IETF. What is this text trying to tell me about how I should handle user identity?

**Comment by gurshabad** [comment]
Thanks, ekr, for delineating the two. I do not think there is disagreement here. First, I agree with ekr that "common for systems to have [some] identifying information in them." The considerations mentioned in the security, privacy, pseudonymity and anonymity are more relevant for that.

However, the context and aim of this particular section is more narrow and is close to "situations in which there is no identifying information and people are talking about adding some for attribution" (as ekr put it). And in these proposals, it is often the case that someone wants communication to be tied to real world identities. That is what is meant by "attribution" in this section.

To put it crudely: the final recommendation that the RG has consensus on is that if you're designing a protocol or system, don't go above and beyond to include mechanisms of attribution to individual users. Further, don't do that in the name of the right to legal remedy, because such mechanisms would be inconsistent with human rights overall.

As Mallory has said, this section was the result of careful RG discussions, and I'd be hesistant to change the recommendation and tone overall. But I sense broad agreement on this thread here, and would welcome a PR that makes the scope of the section clearer.

**Comment by ekr** [comment]
See https://github.com/IRTF-HRPC/draft-guidelines/pull/13

**Comment by nllz** [comment]
I appreciate the PR, but adding "real names policies" as an example is perhaps a bit problematic. Could we perhaps remove that? There have been extensive discussions about this policy on platforms so perhaps we don't need to import that here? Rest seems totally fine with me!

**Comment by gurshabad** [comment]
Thanks, both.

**Comment by ekr** [comment]
@gurshabad please re-open this. I think the PR I made was useful but I don't believe it resolves this and I'd like to hear from the chairs first.

**Comment by gurshabad** [comment]
Sure.

**Comment by nllz** [comment]
As per the separate email thread:

I have been mulling over this today and I think I get the problem. This para solely considers adding PII to data streams with the aim to enable access to remedy. This para does not discuss other cases (such as using source IP addresses (which are not created/added to enable access to remedy)). To make this more concrete and address your concern I would like to propose the following text:

Considering the potential adverse impact of attribution on the right to privacy and freedom of expression, enabling attribution on an individual level is most likely not consistent with human rights.

Example: Adding personally identifiable information to data streams as a means to enable the human right to remedy might help in identifying a violator of human rights and provide access to remedy, but this would disproportionally affect all users right to privacy, anonymous expression, and association.

**Comment by nllz** [comment]
https://github.com/IRTF-HRPC/draft-guidelines/commit/04ed2aa5a2e079fa0f129b902c3914c0a30015bb

**Comment by nllz** [comment]
I propose we move the discussion back to the hrpc list based on: https://datatracker.ietf.org/doc/html/draft-irtf-hrpc-guidelines-19

**Comment by ekr** [comment]
I don't love the text here but in the interest of progress, I think I can live with it. Authors feel free to close.
