### ISSUE TITLE
Pseudonymity vs. Anonymity

### ISSUE THREAD

**Issue by ekr** [IRTF-HRPC/draft-guidelines#7]
I think the text around anonymity and pseudonymity is very confusing
because it is difficult to cleanly separate these two concepts. In
particular, both sections talk about IP addressed based
identifiers. What kind of identifier do you think an IP address is?
It seems to me that that there is an argument for either in this
context, depending on how it is assigned (e.g., home versus mobile).

I find the discussion of ODoH particularly confusing because that is
not about pseudonymity but about simply deleting the IP address, so
why isn't this in anonymity?

IMO this text should be restructured to address the relevant
privacy concepts, and in particular that identifiers are on
a continuum of space (the number of people who it might refer
to), time (the stability of the identifier), and locality
(the set of contexts in which they apply). Once you have done
that, I think it will be easier to locate the various points
in the spectrum and discuss the various countermeasures.

>   Example: Generally, pseudonymous identifiers cannot be simply reverse
   engineered.  Some early approaches took approaches such as simple
   hashing of IP addresses, but these could then be simply reversed by
   generating a hash for each potential IP address and comparing it to
   the pseudonym.

This is not entirely true for v6 addresses.

You should replace the reference to ODoH with one to O-HTTP.

**Comment by gurshabad** [comment]
Thanks, @ekr. Replacing the reference to ODoH to O-HTTP.

I think for the other stuff, I don't disagree at all. A great starting point that I would welcome is a PR on this issue, whenever you have time.

**Comment by ekr** [comment]
SG. I'll try to work something up this week. Can you please assign this to me and mark it PR-Wanted (I don't have permissions).

**Comment by ekr** [comment]
I don't think this is completed. Please re-open.

**Comment by nllz** [comment]
Ah ok - sorry about that. There is no PR for this yet, right?

**Comment by nllz** [comment]
We are still waiting for a PR from @ekr on this, right?

**Comment by ekr** [comment]
Yes. I have the AI on this.

**Comment by ekr** [comment]
See https://github.com/IRTF-HRPC/draft-guidelines/pull/12

**Comment by gurshabad** [comment]
Excellent edits, thank you!
